- name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: 22
- name: Enable corepack
  run: |
    npm i -g --force corepack
    corepack enable
    corepack install --global yarn@stable 
- name: Setup Node with Yarn Cache
  uses: actions/setup-node@v4
  env:
    SKIP_YARN_COREPACK_CHECK: true
  with:
    node-version: 22
    cache: 'yarn'
    cache-dependency-path: 'frontend/package.json'
