[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
github-build-setup = "../build-setup.yml"
# Which actions to run on pull requests
pr-run-mode = "upload"
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "1.0.0-rc.1+kxxt.8"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl", "aarch64-pc-windows-msvc", "x86_64-apple-darwin", "loongarch64-unknown-linux-gnu", "powerpc64le-unknown-linux-gnu", "powerpc64le-unknown-linux-musl", "riscv64gc-unknown-linux-gnu", 
"x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

[dist.github-custom-runners.loongarch64-unknown-linux-gnu.container]
image = "ghcr.io/kxxt/loongarch64-linux-gnu-runner:latest"

[dist.github-custom-runners]
riscv64gc-unknown-linux-gnu = "ubuntu-22.04"